### ISSUE TITLE
Links Overflowing Popup Box

### ISSUE THREAD

**Issue by AnanteshG** [AnanteshG/Flex-Folio#1]
In the Links section of the popup box, links are extending beyond the boundaries of the popup box when their length exceeds the width of the box. This issue results in the links being cut off or not fully visible. The popup box should be styled to ensure that long links are properly wrapped or truncated to fit within the box's dimensions, maintaining both readability and a clean layout.

Attached are the Images for reference :

![image](https://github.com/user-attachments/assets/3db61bfa-8c2b-431d-8b9e-3528a607ffc3)

![image](https://github.com/user-attachments/assets/e65ef564-4de3-4910-86ae-bde62b4a8305)

**Comment by ppranay20** [comment]
@AnanteshG hey I fixed the issue and made a pr.
